apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.27
        env: 
        - name: MYSQL_DATABASE
          value: devops-db
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: app-secrets
                key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: app-secrets
                key: mysql-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: app-secrets
                key: mysql-root-password
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306