apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-nginx-conf
data:
  php-fpm-conf: |
    server {
        listen 80 default_server;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        index index.php;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        error_page 404 /index.php;

        location ~ \.php$ {
            fastcgi_pass backend-service:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/code/public/$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend-deployment
  labels:
    app: nginx-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-backend
  template:
    metadata:
      labels:
        app: nginx-backend
    spec:
      volumes: 
      - name: backend-nginx-conf
        configMap:
          name: backend-nginx-conf
          items:
            - key: php-fpm-conf
              path: default.conf
      containers:
      - name: nginx-backend
        image: nginx:1.21.5
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          readOnly: true
          name: backend-nginx-conf
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-backend-service
spec:
  selector:
    app: nginx-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80