# This is a basic workflow that is manually triggered

name: Build & deploy backend

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '**/workflows/backend.yml'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.14'
        tools: composer
    - run: composer install