# This workflow builds, tests, lints and deploys the frontend
name: Build & deploy Frontend

# Workflow is triggered on frontend commit/push
on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '**/workflows/frontend.yml'

jobs:
  # This job builds, tests, lints and packages the artifact for the image job
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.2'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Installing dependecies
      run: npm ci

    - name: Building production bundle
      run: npm run build
      env:
        REACT_APP_API_ENDPOINT_URL: ${{secrets.REACT_APP_API_ENDPOINT_URL}}

    - name: Running tests
      run: npm test

    - name: Running lint
      run: npm run lint

    - name: Uploading build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: frontend/build

  # This job build docker image and publishes it in DockerHub
  image:
    name: Build & Publish image in DockerHub
    runs-on: ubuntu-latest
    needs: build
    environment: production
    
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Uploading build artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: infrastructure/frontend/build

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get latest commit sha
      id: get-sha
      run: echo "::set-output name=short-sha::$(git rev-parse --short HEAD)"

    - name: Build and publish docker image
      uses: docker/build-push-action@v2
      with:
        context: infrastructure/frontend
        push: true
        tags: chavdarb/devops-sample-frontend:${{steps.get-sha.outputs.short-sha}},chavdarb/devops-sample-frontend:latest

    - name: Scan image for vulnerabilities
      uses: azure/container-scan@v0
      with:
        image-name: chavdarb/devops-sample-frontend:${{steps.get-sha.outputs.short-sha}}

  # This job deploys frontend to K8s
  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    needs: image
    environment: production

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Setup kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: v1.23.2

    - name: Connect to K8s cluster
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Get latest commit sha
      id: get-sha
      run: echo "::set-output name=short-sha::$(git rev-parse --short HEAD)"

    - name: Deploy frontend to K8s cluster
      uses: Azure/k8s-deploy@v1.4
      with:
        manifests: infrastructure/frontend.yaml
        images: 'chavdarb/devops-sample-frontend:${{steps.get-sha.outputs.short-sha}}'