# This workflow manages the K8s infrastructure

name: Deploy Infrastructure

# Workflow is triggered on infrastructure commit/push
on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - '**/workflows/infrastructure.yml'

jobs:
  # This job deploys K8s infrastructure
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2

    - name: Setup kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: v1.23.2

    - name: Configure connection to K8s cluster
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Set cluster secrets
      uses: azure/k8s-create-secret@v2
      with:
        secret-type: 'generic'
        secret-name: 'app-secrets'
        data: ${{ secrets.APP_SECRETS}}

    - name: Deploy infrastructure
      uses: Azure/k8s-deploy@v1.4
      with:
        manifests: |
            infrastructure/storage.yaml
            infrastructure/mysql.yaml
            infrastructure/backend.yaml
            infrastructure/frontend.yaml
            infrastructure/nginx-backend.yaml