# This is a basic workflow that is manually triggered

name: Deploy infrastructure

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - '**/workflows/infrastructure.yml'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - uses: azure/setup-kubectl@v2.0
      with:
        version: v1.23.2
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - uses: Azure/k8s-deploy@v1.4
      with:
        manifests: |
            infrastructure/mysql.yaml
            infrastructure/backend.yaml
            infrastructure/frontend.yaml
            infrastructure/db-migrate.yaml
            infrastructure/nginx-backend.yaml